<?php
$postUrl      = $this->getUrl('sveacheckout/index/updateCart');
$locales      = $block->getLocales();
$country      = $locales['purchase_country'];
$clearStorage = $block->getClearLocalStorage();
?>
<div class="svea-checkout">
    <div class="loading-wrapper">
        <div class="loading-text">
            <?= __('Please wait...') ?>
        </div>
    </div>
    <?= $block->getCheckoutHtml() ?>
</div>
<style type="text/css">
    <?php if ($block->getAllowCountrySwitching()): ?>
    #shipping-zip-form > fieldset > p.note,
    #shipping-zip-form > fieldset > div[name="shippingAddress\.region"],
    #shipping-zip-form > fieldset > div[name="shippingAddress\.postcode"] {
          display: none;
    }

    #shipping-zip-form > fieldset > div[name="shippingAddress\.country_id"] {
        display: block;
    }
    <?php else: ?>
    #shipping-zip-form {
        display: none;
    }
    <?php endif; ?>
</style>
<script>// <![CDATA[
  require([
    'sveacheckout'
  ], function ($, script) {
    if('true' == '<?= $clearStorage ?>') {
      localStorage.clear();
    }
    sveacheckout = {
      // ajax post path
      postUrl: '<?= $postUrl ?>',
      country: '<?= $country ?>',

      // map block ids
      blockIds: [
        {name: 'snippet',       id: 'svea-checkout-container'},
          /* {name: 'totalsBlock',   id: 'cart-totals'}, */
        {name: 'shippingBlock', id: 'cart-shipping'},
          /* {name: 'couponBlock',   id: 'cart-coupon'}, */
        {name: 'cartBlock',     id: 'shopping-cart-table'},
      ],
    };
  });
// ]]>
</script>
