<?php
if ($info = $block->getData()) {
    $additional = $info['info']['additional_information'];
    $title      = $additional['method_title'];

    if (isset($additional['OrderId'])) {
        $mode              = ('prod' == $additional['mode'])
            ? '<span style="color: green; font-weight: bold">LIVE</span>'
            : '<span style="color: red;   font-weight: bold">TEST</span>';
        $willBuy           = $additional['SveaWillBuyOrder'];
        $type              = $additional['PaymentType'];
        $reference         = $additional['ClientOrderNumber'];
        $orderId           = $additional['OrderId'];
        $customerReference = $additional['CustomerReference'];
    } elseif (isset($additional['reservation']['OrderId'])) {
        $mode              = ('prod' == $additional['sveacheckout']['mode'])
            ? '<span style="color: green; font-weight: bold">LIVE</span>'
            : '<span style="color: red;   font-weight: bold">TEST</span>';
        $willBuy           = $additional['reservation']['SveaWillBuyOrder'];
        $type              = $additional['reservation']['PaymentType'];
        $orderReference    = $additional['reservation']['ClientOrderNumber'];
        $orderId           = $additional['reservation']['OrderId'];
        $customerReference = $additional['reservation']['CustomerReference'];
    } else {
        $type = __('Not acknowledged');
        $mode = '<span style="color: gray; font-weight:bold">Unknown</span>';
    }
    ?>
    <img src="http://cdn.svea.com/sveaekonomi/rgb_ekonomi_large.png" alt="<?php echo $title ?>"/>
    <br/>
    <table class="data-grid">
        <thead>
        <tr>
            <th>Key</th>
            <th>Value</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($orderId)) : ?>
            <tr>
                <td><b><?php echo __('Svea Order ID') ?></b></td>
                <td><?php echo $orderId ?></td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($customerReference)) : ?>
            <tr>
                <td><b><?php echo __('Reference') ?></b></td>
                <td><?php echo $customerReference ?></td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($orderReference)) : ?>
            <tr>
                <td><b><?php echo __('Magento ID') ?></b></td>
                <td><?php echo $orderReference ?></td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($willBuy)) : ?>
            <tr>
                <td><b><?php echo __('Bought invoice') ?></b></td>
                <td><?php echo __($willBuy) ?></td>
            </tr>
        <?php endif; ?>
        <tr>
            <td><b><?php echo __('PaymentType') ?></b></td>
            <td><?php echo __($type) ?></td>
        </tr>
        <tr>
            <td><b><?php echo __('Mode') ?></b></td>
            <td><?php echo __($mode) ?></td>
        </tr>
        </tbody>
    </table>
    <?php
}
?>